### ISSUE TITLE
Sveltekit and SSR crash

### ISSUE THREAD

**Issue by Patrickkpic** [andrew-secret/svelte-datepicker#101]
Does not work with Sveltekit and SSR (even with SPA mode: static-adapter).
It simply crashes the page

**Logs**
on the page:
500
Failed to fetch dynamically imported module: http://localhost:3000/src/routes/about.svelte?t=1631803862284
TypeError: Failed to fetch dynamically imported module: http://localhost:3000/src/routes/about.svelte?t=1631803862284

in the terminal:
16:45:40 [vite] Error when evaluating SSR module /Users/xxx/projects/xxx/src/routes/about.svelte:

Error: failed to load module for ssr: /node_modules/svelte-inclusive-datepicker/src/index.js
    at instantiateModule (/Users/xxx/projects/xxx/node_modules/vite/dist/node/chunks/dep-98dbe93b.js:73805:15)
failed to load module for ssr: /node_modules/svelte-inclusive-datepicker/src/index.js

**To Reproduce**
Install basic Sveltekit project
follow the install instructions here and choose date-fns

  import { DatePicker } from 'svelte-inclusive-datepicker';
in a random .svelte route

**Comment by leetrout** [comment]
Similar error

```
6:16:29 PM [vite] Error when evaluating SSR module /node_modules/date-fns/locale/en-US/index.js?v=e6530e82:
ReferenceError: exports is not defined
    at /node_modules/date-fns/locale/en-US/index.js?v=e6530e82:3:23
    at instantiateModule (/home/user/code/github.com/10trinsic/10trinsic.com/node_modules/vite/dist/node/chunks/dep-4b9dfa16.js:60093:15)
    ```

**Comment by leetrout** [comment]
Probably related to https://github.com/vitejs/vite/issues/2579

**Comment by andrew-secret** [comment]
Apologies for the delayed response. It seems though this issue https://github.com/vitejs/vite/issues/2579 might be related. Otherwise, you are welcome to create a pull request. I'll try to look into it.

First thing first, I'll update all the dependencies and close those open Dependabot PR's. Makes my happy to see that people actually using this and starting to contribute to it.
